version: '2.4'
services:
  web:
    depends_on:
      - db
    container_name: swapi.web
    build: .
    command: export NODE_OPTIONS="--max-old-space-size=4096"
    ports:
      - "3000:3000"
    mem_limit: 256m
    memswap_limit: 4g

  db:
    container_name: swapi.mysql
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mysql
    ports:
      - 3106:3306
    volumes:
      - swapi-mysql:/var/lib/mysql

  caddy:
    image: caddy:2.7-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/site:/srv
      - ./caddy/caddy_data:/data
      - ./caddy/caddy_config:/config

volumes:
  swapi-mysql:
    driver: local
