version: '3'
services:
  web:
    depends_on:
      - db
    container_name: swapi.web
    build: .
    command: npm start
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 1024M

  db:
    container_name: swapi.mysql
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mysql
    ports:
      - 3106:3306
    volumes:
      - swapi-mysql:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 512M

  caddy:
    image: caddy:2.7-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/site:/srv
      - ./caddy/caddy_data:/data
      - ./caddy/caddy_config:/config


volumes:
  swapi-mysql:
    driver: local